version: "3.9"
services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC

    volumes:
      - /data/config/calibre:/config
      - /data/media/books:/books
    ports:
      - 8083:8080
      - 8181:8181
      - 8082:8081
    restart: unless-stopped
