version: "3.9"
services:
  portainer:
    container_name: portainer
    restart: unless-stopped
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - /data/config/portainer:/config
      - /var/run/docker.sock:/var/run/docker.sock
    image: portainer/portainer-ce
